version: "3"
services:
  master:
    build: .
    volumes:
      - ./src/locustfile.py:/locust/locustfile.py
    command: -H https://yourdomain.example.com --master
    ports:
      - "8089:8089"
  slave:
    build: .
    volumes:
      - ./src/locustfile.py:/locust/locustfile.py
    command: --slave --master-host=master
    depends_on:
      - master